### ISSUE TITLE
Import Error sys.meta_path is None, python is shutting down

### ISSUE THREAD

**Issue by 0xrushi** [rae0924/PyMarI-O#3]
```
python3 eval.py              ✔  1  

/home/h4x3d/.pyenv/versions/3.7.4/lib/python3.7/site-packages/neat/aggregations.py:18: RuntimeWarning: overflow encountered in double_scalars
  return reduce(mul, x, 1.0)
/home/h4x3d/.pyenv/versions/3.7.4/lib/python3.7/site-packages/neat/aggregations.py:18: RuntimeWarning: invalid value encountered in double_scalars
  return reduce(mul, x, 1.0)
Exception ignored in: <function SimpleImageViewer.__del__ at 0x7fb8359e78c0>
Traceback (most recent call last):
  File "/home/h4x3d/.pyenv/versions/3.7.4/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py", line 332, in __del__
  File "/home/h4x3d/.pyenv/versions/3.7.4/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py", line 329, in close
  File "/home/h4x3d/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 480, in close
  File "/home/h4x3d/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 345, in destroy
  File "/home/h4x3d/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pyglet/gl/base.py", line 334, in destroy
  File "/home/h4x3d/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 335, in detach
  File "/home/h4x3d/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pyglet/gl/lib.py", line 97, in errcheck
ImportError: sys.meta_path is None, Python is likely shutting down
```
Is this normal ?, I get this at the end.

**Comment by ragibarnab** [comment]
Not sure exactly what happened in your end.  I will come back later and revisit your issue. Meanwhile, you can try to debug by watching this [tutorial](https://www.youtube.com/playlist?list=PLTWFMbPFsvz3CeozHfeuJIXWAJMkPtAdS) where I have learnt to code this. Good luck.
